const DEFAULT_REVIEWER_PROMPT = `STRICT_CODE_REFINER_MODE:
You are an elite Staff Frontend Engineer acting as Agent 3 in an AI UI Generation pipeline.
Your task is to take a raw React/Tailwind component tree generated by another AI and audit/refine it.

CRITICAL PIPELINE RULES:
1. SINGLE BLOCK ONLY: Return ONLY the final polished executable React file. Do not use multiple code blocks.
2. NO TEXT: Do not write explanations, markdown outside the code block, or "Here is the code".
3. SELF-CORRECTION: Scan the code for:
   - Syntax errors or unclosed React tags.
   - Missing or conflicting Tailwind CSS classes.
   - Poor accessibility (missing aria-labels, bad focus states).
   - Incomplete functional hooks or stubbed-out logic that will break rendering.
4. PREMIUM POLISH: Ensure the Dark Glassmorphism aesthetic is fully realized (cyan/purple accents, nice backdrops, consistent padding).

Your output MUST be the complete, corrected, and refined code ready to be injected into a live Babel environment.`;

export async function reviewCodeAndRefine(code: string, structuredJson: any): Promise<string> {
  const API_KEY = process.env.NEXT_PUBLIC_GEMINI_API_KEY || "";
  
  if (!API_KEY) {
    throw new Error("Missing AI Provider API Key for Reviewer");
  }

  const isGroq = API_KEY.trim().startsWith("gsk_");
  const isXai = API_KEY.trim().startsWith("xai-");
  
  const providerLabel = isGroq ? "Groq" : isXai ? "xAI (Grok)" : "Gemini";
  const keySuffix = API_KEY.length > 5 ? `...${API_KEY.slice(-5)}` : "unknown";
  
  console.log(`[REVIEWER] Provider Detected: ${providerLabel} (Key: ${keySuffix})`);

  const promptContent = `STRUCTURED_REQUIREMENTS:
${JSON.stringify(structuredJson, null, 2)}

RAW_GENERATED_CODE:
\`\`\`tsx
${code}
\`\`\`

Refine, fix, and enhance the provided code. Return only the final executable file.`;

  let text = "";

  if (isGroq || isXai) {
    const modelName = isGroq ? "llama-3.3-70b-versatile" : "grok-beta";
    const apiUrl = isGroq ? "https://api.groq.com/openai/v1/chat/completions" : "https://api.x.ai/v1/chat/completions";

    console.log(`[REVIEWER] Calling ${providerLabel} API: ${modelName}`);

    const aiResponse = await fetch(apiUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${API_KEY.trim()}`,
      },
      body: JSON.stringify({
        model: modelName,
        messages: [
          { role: "system", content: DEFAULT_REVIEWER_PROMPT },
          { role: "user", content: promptContent }
        ],
        temperature: 0.1, // Slight flexibility for creative CSS polishing
      }),
    });

    if (!aiResponse.ok) {
      const errorData = await aiResponse.json();
      throw new Error(`${providerLabel} Error in Reviewer: ${errorData.error?.message || aiResponse.statusText}`);
    }

    const data = await aiResponse.json();
    text = data.choices[0].message.content;
  } else {
    // Gemini
    const { GoogleGenerativeAI } = await import("@google/generative-ai");
    const genAI = new GoogleGenerativeAI(API_KEY);
    const model = genAI.getGenerativeModel({ model: "gemini-1.5-pro" }); // Using Pro for reviewing instead of Flash for better reasoning
    
    console.log("REVIEWER [Gemini]: Synthesizing with gemini-1.5-pro");
    
    const result = await model.generateContent(`${DEFAULT_REVIEWER_PROMPT}\n\n${promptContent}`);
    text = result.response.text();
  }

  // Parse Multi-Block Selection Logic
  let refinedCode = "";
  const codeBlocks = Array.from(text.matchAll(/```(?:tsx|jsx|javascript|typescript|react|html|css)?\n([\s\S]*?)```/g)).map(m => m[1].trim());
  
  if (codeBlocks.length > 0) {
    // Prioritize the block that looks like a React component
    const reactBlock = codeBlocks.find(b => 
      (b.includes("export default") || b.includes("return (")) && 
      !b.includes("### CSS")
    );
    refinedCode = reactBlock || codeBlocks[0];
  } else {
    // Fallback if AI returned raw code without backticks
    if (text.includes("export default") || (text.includes("<") && text.includes(">"))) {
      refinedCode = text.trim();
    } else {
      console.warn("[REVIEWER] Failed to extract clean code, falling back to original code.");
      return code; // If reviewer fails structure, safely fallback to what generator initially provided
    }
  }

  return refinedCode;
}
